# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  "setup":
    docker:
      - image: instapy/instapy
    working_directory: ~/instaBot
    steps:
      - checkout
      - run:
          name: "Test"
          command: |
            pwd
      - run:
          name: "Run Bot"
          command: |
            python3 ./instabot.py
      - run:
          name: "End"
          command: |
            echo "End"
  
workflows:
  version: 2
  build:
    jobs:
      - "setup"
