# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  "setup":
    docker:
      - image: instapy/instapy
    working_directory: ~/instaBot
    steps:
      - checkout
      - run:
          name: "Run Bot"
          command: |
            echo ""
workflows:
  version: 2
  build:
    jobs:
      - "setup"
